name: Create Repo for RustDesk ALL

on:
  schedule:
     #Every day at 3AM UTC
    - cron: "0 3 * * *"
  workflow_dispatch:

env:
    REPO_NAME_LATEST: xlion-rustdesk-latest-apt-repo
    REPO_NAME_NIGHTLY: xlion-rustdesk-nightly-apt-repo
    CODENAME: main
    COMPONENTS: main
    ARCHITECTURES: amd64 arm64 armhf i386
    # armhf is ARMv7 (32bit) 
  
jobs:
    verify:
      name: Verify container
      runs-on: ubuntu-latest
      steps:
        - name: Install Cosign
          uses: sigstore/cosign-installer@v3.7.0

        - name: Verify
          run: |
            cosign verify --rekor-url=https://rekor.sigstore.dev \
            --certificate-identity-regexp "https://github.com/xlionjuan/.*" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            ghcr.io/xlionjuan/fedora-createrepo-image-minimal:latest

    build-latest:
      name: Build latest
      needs: verify
      runs-on: ubuntu-latest
      container: ghcr.io/xlionjuan/fedora-createrepo-image-minimal:latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Download RustDesk
          run: dpkg-deb --build rustdesk-server-meta rustdesk-server-meta.deb & bash rustdesk_latest.sh & bash rustdesk-server_latest.sh

        - uses: xlionjuan/apt-repo-action@main
          id: create-apt-repo_latest
          with:
            repo-name: ${{ env.REPO_NAME_LATEST }}
            signing-key: ${{ secrets.SIGNING_KEY }}
            codename: ${{ env.CODENAME }}
            components: ${{ env.COMPONENTS }}
            architectures: ${{ env.ARCHITECTURES }}
            override: ./override # the location of the file within your repo, thats why checkout is needed before
        
        - name: Publish Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: latest
            path: ${{ steps.create-apt-repo_latest.outputs.dir }}
            if-no-files-found: error


    build-nightly:
      name: Build nightly
      needs: verify
      runs-on: ubuntu-latest
      container: ghcr.io/xlionjuan/fedora-createrepo-image-minimal:latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Download RustDesk
          run: bash rustdesk_nightly.sh

        - uses: xlionjuan/apt-repo-action@main
          id: create-apt-repo_nightly
          with:
            repo-name: ${{ env.REPO_NAME_NIGHTLY }}
            signing-key: ${{ secrets.SIGNING_KEY }}
            codename: ${{ env.CODENAME }}
            components: ${{ env.COMPONENTS }}
            architectures: ${{ env.ARCHITECTURES }}
        
        - name: Publish Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: nightly
            path: ${{ steps.create-apt-repo_nightly.outputs.dir }}
            if-no-files-found: error



    deploy:
      name: Push to Cloudflare R2
      runs-on: ubuntu-latest
      needs: 
        - build-latest
        - build-nightly
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Download artifact latest
          uses: actions/download-artifact@v4
          with:
            pattern: latest
            path: wwwroot/latest
            merge-multiple: true

        - name: Download artifact nightly
          uses: actions/download-artifact@v4
          with:
            pattern: nightly
            path: wwwroot/nightly
            merge-multiple: true
    
        - name: Upload to Cloudflare R2
          uses: ryand56/r2-upload-action@latest
          with:
            r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
            r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
            r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
            r2-bucket: ${{ secrets.R2_BUCKET }}
            keep-file-fresh: true
            source-dir: wwwroot
            destination-dir: ./
